version: '3.4'
services:
  tracker:
    image: ergo/dex-tracker:latest
    build:
      context: .
      dockerfile: modules/dex-tracker/Dockerfile
  matcher:
    image: ergo/dex-matcher:latest
    build:
      context: .
      dockerfile: modules/dex-matcher/Dockerfile
  executor:
    image: ergo/dex-executor:latest
    build:
      context: .
      dockerfile: modules/dex-executor/Dockerfile